# Generated by Django 2.1.4 on 2018-12-26 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='author',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
