# Generated by Django 2.1.4 on 2018-12-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2c', '0002_auto_20181226_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='telephone',
            field=models.CharField(max_length=100),
        ),
    ]
